[project]
name = "inspect-ai-examples"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aioboto3>=15.0.0",
    "inspect-ai>=0.3.108",
    "openai>=1.107.3",
]
